# Generated by Django 4.2 on 2023-05-18 11:48

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_authors_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(upload_to=book.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=book.models.content_file_name),
        ),
    ]
